name: Build and Test

on:
  push:
    tags:
      - "v+[0-9]+.[0-9]+.[0-9]+"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21.0

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
        draft: false
        prerelease: false
        token: ${{ secrets.GH_TOKEN }}
        generate_release_notes: true
        make_latest: true
