name: Create Release

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Tag
        id: extract_tag
        run: |
          echo "TAG_NAME=$(echo ${{ github.event.workflow_run.head_commit.message }} | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          token: ${{ secrets.GH_TOKEN }}
          generate_release_notes: true
          make_latest: true
